// packages/solid/src/index.ts
import type { Atom } from 'atomous'
import { from } from 'solid-js'

/**
 * Create a readable signal from atom.
 *
 * @example
 * const $count = atom(0)
 *
 * function Counter() {
 *   const count = fromAtom($count)
 *
 *   function increment() {
 *     $count.update(count => count + 1)
 *   }
 *
 *   return <button onClick={increment}>Count is {count()}</button>
 * }
 */
export function fromAtom<TValue>(atom: Atom<TValue>) {
  return from((set) => {
    return atom.subscribe(value => set(() => value))
  }, atom.get())
}

// packages/react/src/index.ts
import type { Atom } from 'atomous'
import { useSyncExternalStore } from 'react'

/**
 * Subscribe and get atom value.
 *
 * @example
 * const $count = atom(0)
 *
 * function Counter() {
 *   const count = useAtomValue($count)
 *
 *   function increment() {
 *     $count.update(count => count + 1)
 *   }
 *
 *   return <button onClick={increment}>Count is {count}</button>
 * }
 */
export function useAtomValue<TValue>(atom: Atom<TValue>) {
  return useSyncExternalStore(atom.subscribe, atom.get, atom.get)
}
